#!/bin/sh
# Generated by kati 12685f9a31b7bd30e20a0cd9b939ea3eb0640d45

export 'MAKE'='/home/rihards/gnu-free-bootstrap/kbuild-kati-stage3-experiment/kati-parallel-experiment/kati-stage3/ckati'
export 'MAKEFLAGS'='-- CC=/tmp/mydistro-experiment-cc HOSTCC=/usr/lib/llvm/22/bin/clang'
export 'MAKEOVERRIDES'='CC=/tmp/mydistro-experiment-cc HOSTCC=/usr/lib/llvm/22/bin/clang'
