#!/bin/sh
# Generated by kati 12685f9a31b7bd30e20a0cd9b939ea3eb0640d45

. ./env.sh
kati_jobs="${KATI_JOBS:-}"
kati_jobs_explicit=0
if [ -n "$kati_jobs" ]; then kati_jobs_explicit=1; fi
default_kati_jobs=12
ninja_jobs=""
prev=""
for arg in "$@"; do
  case "$arg" in
    -j[0-9]*) ninja_jobs="${arg#-j}" ;;
    -j=*) ninja_jobs="${arg#-j=}" ;;
    -j) prev="-j" ;;
    [0-9]*) if [ "$prev" = "-j" ]; then ninja_jobs="$arg"; prev=""; fi ;;
    *) prev="" ;;
  esac
done
if [ "$kati_jobs_explicit" -eq 0 ]; then
  kati_jobs="${ninja_jobs:-$default_kati_jobs}"
fi
if [ -n "$kati_jobs" ]; then export KATI_JOBS="$kati_jobs"; fi
kati_fifo=""
if [ -z "${KATI_JOBSERVER_FIFO:-}" ]; then
  case "$kati_jobs" in ''|0|*[!0-9]*) kati_jobs=1; export KATI_JOBS=1 ;; esac
  kati_fifo_base="${TMPDIR:-/tmp}/kati-jobserver-$$"
  kati_fifo="$kati_fifo_base"
  kati_fifo_i=0
  while ! (umask 077 && mkfifo "$kati_fifo") 2>/dev/null; do
    kati_fifo_i=$((kati_fifo_i + 1))
    kati_fifo="$kati_fifo_base-$kati_fifo_i"
  done
  exec 9<>"$kati_fifo"
  kati_i=0
  while [ "$kati_i" -lt "$kati_jobs" ]; do printf x >&9; kati_i=$((kati_i + 1)); done
  export KATI_JOBSERVER_FIFO="$kati_fifo"
  trap 'if [ -n "${kati_fifo:-}" ]; then rm -f "$kati_fifo"; fi' EXIT HUP INT TERM
fi
kati_ninja_pid=""
kati_cleanup() {
  if [ -n "$kati_ninja_pid" ]; then kill -TERM "$kati_ninja_pid" 2>/dev/null || :; fi
  if [ -n "${kati_fifo:-}" ]; then rm -f "$kati_fifo"; fi
}
trap 'kati_cleanup; exit 129' HUP INT TERM
ninja -f ./build.ninja "$@" &
kati_ninja_pid=$!
wait "$kati_ninja_pid"
kati_status=$?
kati_ninja_pid=""
trap - HUP INT TERM
if [ -n "$kati_fifo" ]; then rm -f "$kati_fifo"; fi
exit $kati_status
