// FORK MODIFICATION NOTICE (2026)
// Changed by the GNU-free Kati fork, maintained by Rihards Paps and
// Haralds Paps.
// Changed build execution, evaluation, or portability for this fork.
// Upstream material retains its Apache-2.0 terms. Fork modifications are
// covered by Mozilla Public License 2.0; see docs/LICENSING.md and NOTICE
// at the repository root. Original notices below remain applicable.

// Copyright 2015 Google Inc. All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// +build ignore

#include "ninja.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <cctype>
#include <fstream>
#include <map>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>

#include "command.h"
#include "dep.h"
#include "eval.h"
#include "exec.h"
#include "file_cache.h"
#include "fileutil.h"
#include "find.h"
#include "flags.h"
#include "func.h"
#include "io.h"
#include "log.h"
#include "stats.h"
#include "stringprintf.h"
#include "strutil.h"
#include "timeutil.h"
#include "var.h"
#include "version.h"

static std::string ShellQuote(std::string_view s) {
  std::string out = "'";
  for (char c : s) {
    if (c == '\'') {
      out += "'\\''";
    } else {
      out += c;
    }
  }
  out += "'";
  return out;
}

static bool EnsureDirectory(std::string_view path) {
  if (path.empty() || path == ".")
    return true;

  std::string current;
  current.reserve(path.size());
  if (path.front() == '/')
    current = "/";
  for (size_t i = 0; i <= path.size(); ++i) {
    if (i < path.size() && path[i] != '/') {
      current += path[i];
      continue;
    }

    if (current.empty() || current == "/")
      continue;

    if (mkdir(current.c_str(), 0777) != 0 && errno != EEXIST)
      return false;

    struct stat st;
    if (stat(current.c_str(), &st) != 0 || !S_ISDIR(st.st_mode))
      return false;

    if (i < path.size() && path[i] == '/')
      current += '/';
  }
  return true;
}

static size_t FindCommandLineFlag(std::string_view cmd, std::string_view name) {
  const size_t found = cmd.find(name);
  if (found == std::string::npos || found == 0)
    return std::string::npos;
  return found;
}

static std::string_view FindCommandLineFlagWithArg(std::string_view cmd,
                                                   std::string_view name) {
  size_t index = FindCommandLineFlag(cmd, name);
  if (index == std::string::npos)
    return std::string_view();

  std::string_view val = TrimLeftSpace(cmd.substr(index + name.size()));
  index = val.find(name);
  while (index != std::string::npos) {
    val = TrimLeftSpace(val.substr(index + name.size()));
    index = val.find(name);
  }

  index = val.find_first_of(" \t");
  return val.substr(0, index);
}

static bool GetDepfileFromCommandImpl(std::string_view cmd, std::string* out) {
  if ((FindCommandLineFlag(cmd, " -MD") == std::string::npos &&
       FindCommandLineFlag(cmd, " -MMD") == std::string::npos) ||
      FindCommandLineFlag(cmd, " -c") == std::string::npos) {
    return false;
  }

  std::string_view mf = FindCommandLineFlagWithArg(cmd, " -MF");
  if (!mf.empty()) {
    out->append(mf);
    return true;
  }

  std::string_view o = FindCommandLineFlagWithArg(cmd, " -o");
  if (o.empty()) {
    ERROR("Cannot find the depfile in %s", std::string(cmd).c_str());
    return false;
  }

  out->append(StripExt(o));
  *out += ".d";
  return true;
}

bool GetDepfileFromCommand(std::string* cmd, std::string* out) {
  CHECK(!cmd->empty());
  if (!GetDepfileFromCommandImpl(*cmd, out))
    return false;

  // A hack for Android - llvm-rs-cc seems not to emit a dep file.
  if (cmd->find("bin/llvm-rs-cc ") != std::string::npos) {
    return false;
  }

  // TODO: A hack for Makefiles generated by automake.

  // A hack for Android to get .P files instead of .d.
  std::string p{StripExt(*out)};
  p += ".P";
  if (cmd->find(p) != std::string::npos) {
    const std::string rm_f = "; rm -f " + *out;
    const size_t found = cmd->find(rm_f);
    if (found == std::string::npos) {
      ERROR("Cannot find removal of .d file: %s", cmd->c_str());
    }
    cmd->erase(found, rm_f.size());
    return true;
  }

  // A hack for Android. For .s files, GCC does not use C
  // preprocessor, so it ignores -MF flag.
  std::string as = "/";
  as.append(StripExt(Basename(*out)));
  as += ".s";
  if (cmd->find(as) != std::string::npos) {
    return false;
  }

  *cmd += "&& cp ";
  *cmd += *out;
  *cmd += ' ';
  *cmd += *out;
  *cmd += ".tmp ";
  *out += ".tmp";
  return true;
}

struct NinjaNode {
  const DepNode* node;
  std::vector<Command> commands;
  int rule_id;
};

static bool IsShellIdentifier(std::string_view name) {
  if (name.empty())
    return false;

  unsigned char first = static_cast<unsigned char>(name[0]);
  if (!(isalpha(first) || first == '_'))
    return false;

  for (size_t i = 1; i < name.size(); i++) {
    unsigned char c = static_cast<unsigned char>(name[i]);
    if (!(isalnum(c) || c == '_'))
      return false;
  }

  return true;
}

class NinjaGenerator {
 public:
  NinjaGenerator(Evaluator* ev, double start_time)
      : ce_(ev),
        ev_(ev),
        rule_id_(0),
        shell_(EscapeNinja(ev->GetShell())),
        shell_flags_(EscapeNinja(ev->GetShellFlag())),
        kati_binary_(GetExecutablePath()),
        start_time_(start_time),
        default_target_(NULL) {
    char cwd[PATH_MAX];
    if (getcwd(cwd, sizeof(cwd)) != nullptr)
      working_dir_ = cwd;
    else
      PERROR("getcwd failed while generating Ninja graph");
    ev_->set_avoid_io(true);
  }

  ~NinjaGenerator() { ev_->set_avoid_io(false); }

  void Generate(const std::vector<NamedDepNode>& nodes,
                const std::string& orig_args) {
    if (g_flags.ninja_dir && !EnsureDirectory(g_flags.ninja_dir))
      ERROR("*** cannot create Ninja output directory: %s", g_flags.ninja_dir);
    unlink(GetNinjaStampFilename().c_str());
    PopulateNinjaNodes(nodes);
    GenerateNinja();
    GenerateShell();
    GenerateStamp(orig_args);
  }

  static std::string GetStampTempFilename() {
    return GetFilename(".kati_stamp%s.tmp");
  }

  static std::string GetFilename(const char* fmt) {
    std::string r = g_flags.ninja_dir ? g_flags.ninja_dir : ".";
    r += '/';
    r += StringPrintf(fmt, g_flags.ninja_suffix ? g_flags.ninja_suffix : "");
    return r;
  }

 private:
  void PopulateNinjaNodes(const std::vector<NamedDepNode>& nodes) {
    ScopedTimeReporter tr("ninja gen (eval)");
    for (auto const& [symbol, depnode] : nodes) {
      PopulateNinjaNode(*depnode);
    }
  }

  void PopulateNinjaNode(const DepNode& node) {
    // GNU make does not execute a rule for an existing target when it has no
    // prerequisites. Ninja treats a zero-input edge as always dirty, which
    // would incorrectly run guard recipes such as Kbuild's "missing .config"
    // diagnostic even when the file is present. FORCE and other explicit
    // prerequisites still enter the graph normally.
    if (done_.exists(node.output)) {
      return;
    }
    done_.insert(node.output);
    active_nodes_.insert(node.output.str());
    ScopedFrame frame(ce_.evaluator()->Enter(
        FrameType::NINJA, node.lexical_output.str(), node.loc));

    // A hack to exclude out phony target in Android. If this exists,
    // "ninja -t clean" tries to remove this directory and fails.
    if (g_flags.detect_android_echo && node.output.str() == "out")
      active_nodes_.erase(node.output.str());
    if (g_flags.detect_android_echo && node.output.str() == "out")
      return;

    // This node is a leaf node
    if (!node.has_rule && !node.is_phony) {
      active_nodes_.erase(node.output.str());
      return;
    }

    NinjaNode& nn = nodes_.emplace_back();
    nn.node = &node;
    nn.commands = ce_.Eval(node);
    nn.rule_id = nn.commands.empty() ? -1 : rule_id_++;

    for (auto const& [symbol, depnode] : node.deps) {
      MarkCycleEdge(node.output, symbol);
      PopulateNinjaNode(*depnode);
    }
    for (auto const& [symbol, depnode] : node.order_onlys) {
      MarkCycleEdge(node.output, symbol);
      PopulateNinjaNode(*depnode);
    }
    for (auto const& [symbol, depnode] : node.validations) {
      MarkCycleEdge(node.output, symbol);
      PopulateNinjaNode(*depnode);
    }
    active_nodes_.erase(node.output.str());
  }

  std::string CycleEdgeKey(Symbol from, Symbol to) const {
    return std::string(from.str()) + "\n" + std::string(to.str());
  }

  void MarkCycleEdge(Symbol from, Symbol to) {
    if (active_nodes_.find(to.str()) != active_nodes_.end())
      cycle_edges_.insert(CycleEdgeKey(from, to));
  }

  bool IsCycleEdge(Symbol from, Symbol to) const {
    return cycle_edges_.find(CycleEdgeKey(from, to)) != cycle_edges_.end();
  }

  std::string_view TranslateCommand(const char* in,
                                    std::string* cmd_buf,
                                    bool preserve_newlines = false) {
    const size_t orig_size = cmd_buf->size();
    bool prev_backslash = false;
    // Set space as an initial value so the leading comment will be
    // stripped out.
    char prev_char = ' ';
    char quote = 0;
    for (; *in; in++) {
      switch (*in) {
        case '#':
          if (quote == 0 && isspace(prev_char)) {
            while (in[1] && *in != '\n')
              in++;
          } else {
            *cmd_buf += *in;
          }
          break;

        case '\'':
        case '"':
        case '`':
          if (quote) {
            if (quote == *in)
              quote = 0;
          } else if (!prev_backslash) {
            quote = *in;
          }
          *cmd_buf += *in;
          break;

        case '$':
          // A recursive make command may deliberately defer a make
          // reference with '$$' so that the child make sees it as a
          // command-line assignment, e.g. CXX=$$(RAW_CXX).  Once the recipe
          // is serialized into Ninja there is no make expansion left in the
          // child process.  Resolve such assignment values while the parent
          // evaluator is still available; otherwise the child receives an
          // empty override and masks its own compiler definition.
          if (in[1] == '(' && quote == '\'' && cmd_buf->size() > orig_size &&
              (*cmd_buf)[cmd_buf->size() - 1] == '=') {
            const char* end = in + 2;
            int depth = 1;
            while (*end && depth != 0) {
              if (*end == '(')
                depth++;
              else if (*end == ')')
                depth--;
              end++;
            }

            if (depth == 0) {
              std::string name(in + 2, end - in - 3);
              Var* var = ev_->LookupVar(Intern(name));
              if (var != nullptr && var->IsDefined()) {
                const std::string value = var->Eval(ev_);
                for (char c : value) {
                  if (c == '$')
                    *cmd_buf += "$$";
                  else
                    *cmd_buf += c;
                }
                in = end - 1;
                break;
              }
            }
          }
          *cmd_buf += "$$";
          break;

        case '\n':
          if (prev_backslash) {
            cmd_buf->resize(cmd_buf->size() - 1);
          } else if (preserve_newlines) {
            // Ninja rule commands are single logical lines.  Preserve the
            // one-shell execution context with a command separator instead
            // of flattening lines into whitespace or emitting invalid Ninja
            // syntax.
            *cmd_buf += "; ";
          } else {
            *cmd_buf += ' ';
          }
          break;

        case '\\':
          *cmd_buf += '\\';
          break;

        default:
          *cmd_buf += *in;
      }

      if (*in == '\\') {
        prev_backslash = !prev_backslash;
      } else {
        prev_backslash = false;
      }

      prev_char = *in;
    }

    if (prev_backslash) {
      cmd_buf->resize(cmd_buf->size() - 1);
    }

    while (cmd_buf->size() > orig_size) {
      char c = (*cmd_buf)[cmd_buf->size() - 1];
      if (c == ';') {
        size_t backslashes = 0;
        for (size_t i = cmd_buf->size() - 1;
             i > orig_size && (*cmd_buf)[i - 1] == '\\'; --i)
          ++backslashes;
        // An escaped semicolon is an argument (e.g. find -exec ... \;),
        // not a redundant shell command separator.
        if (backslashes % 2 != 0)
          break;
      } else if (!isspace(static_cast<unsigned char>(c))) {
        break;
      }
      cmd_buf->resize(cmd_buf->size() - 1);
    }

    return std::string_view(cmd_buf->data() + orig_size,
                            cmd_buf->size() - orig_size);
  }

  bool IsOutputMkdir(const char* name, std::string_view cmd) {
    if (!HasPrefix(cmd, "mkdir -p ")) {
      return false;
    }
    cmd = cmd.substr(9, cmd.size());
    if (!cmd.empty() && cmd.back() == '/') {
      cmd.remove_suffix(1);
    }

    // The command may create the directory target itself (for example,
    // FFmpeg's libavcodec/ rule).  Only elide mkdir for a different output
    // located inside the directory.
    std::string_view output(name);
    while (!output.empty() && output.back() == '/')
      output.remove_suffix(1);
    if (cmd == output)
      return false;

    std::string_view dir = Dirname(name);
    if (cmd == dir) {
      return true;
    }
    return false;
  }

  bool GetDescriptionFromCommand(std::string_view cmd, std::string* out) {
    if (!HasPrefix(cmd, "echo ")) {
      return false;
    }
    cmd = cmd.substr(5, cmd.size());

    bool prev_backslash = false;
    char quote = 0;
    std::string out_buf;

    // Strip outer quotes, and fail if it is not a single echo command
    for (std::string_view::iterator in = cmd.begin(); in != cmd.end(); in++) {
      if (prev_backslash) {
        prev_backslash = false;
        out_buf += *in;
      } else if (*in == '\\') {
        prev_backslash = true;
        out_buf += *in;
      } else if (quote) {
        if (*in == quote) {
          quote = 0;
        } else {
          out_buf += *in;
        }
      } else {
        switch (*in) {
          case '\'':
          case '"':
          case '`':
            quote = *in;
            break;

          case '<':
          case '>':
          case '&':
          case '|':
          case ';':
            return false;

          default:
            out_buf += *in;
        }
      }
    }

    *out = out_buf;
    return true;
  }

  void GenShellScript(const char* name,
                      const std::vector<Command>& commands,
                      std::string* cmd_buf,
                      std::string* description,
                      bool preserve_newlines = false) {
    bool got_descritpion = false;
    auto command_count = commands.size();
    for (const Command& c : commands) {
      size_t cmd_begin = cmd_buf->size();

      if (!cmd_buf->empty()) {
        *cmd_buf += " && ";
      }

      std::string encoded_script;
      if (preserve_newlines) {
        encoded_script = "eval \"$(printf '%s\\n'";
        size_t start = 0;
        while (start <= c.cmd.size()) {
          const size_t end = c.cmd.find('\n', start);
          encoded_script +=
              " " + ShellQuote(c.cmd.substr(start, end == std::string::npos
                                                       ? std::string::npos
                                                       : end - start));
          if (end == std::string::npos)
            break;
          start = end + 1;
        }
        encoded_script += ")\"";
      }
      const char* in =
          preserve_newlines ? encoded_script.c_str() : c.cmd.c_str();
      while (isspace(*in))
        in++;

      bool needs_subshell =
          (command_count > 1 || c.ignore_error) && !c.force_no_subshell;

      if (needs_subshell)
        *cmd_buf += '(';

      std::string_view translated =
          TranslateCommand(in, cmd_buf, preserve_newlines);
      if (g_flags.detect_android_echo && !got_descritpion && !c.echo &&
          GetDescriptionFromCommand(translated, description)) {
        got_descritpion = true;
        translated = std::string_view();
      } else if (IsOutputMkdir(name, translated) && !c.echo && cmd_begin == 0) {
        translated = std::string_view();
      }
      if (translated.empty()) {
        cmd_buf->resize(cmd_begin);
        command_count -= 1;
        continue;
      }

      if (c.ignore_error) {
        *cmd_buf += " ; true";
      }

      if (needs_subshell)
        *cmd_buf += " )";
    }
  }

  bool GetDepfile(const DepNode* node,
                  std::string* cmd_buf,
                  std::string* depfile) {
    if (node->depfile_var) {
      node->depfile_var->Eval(ev_, depfile);
      return true;
    }
    if (!g_flags.detect_depfiles)
      return false;

    *cmd_buf += ' ';
    bool result = GetDepfileFromCommand(cmd_buf, depfile);
    cmd_buf->resize(cmd_buf->size() - 1);
    return result;
  }

  void EmitDepfile(const NinjaNode& nn,
                   std::string* cmd_buf,
                   std::ostream& out) {
    const DepNode* node = nn.node;
    std::string depfile;
    if (!GetDepfile(node, cmd_buf, &depfile))
      return;
    out << " depfile = " << depfile << "\n";
    out << " deps = gcc\n";
  }

  void EmitNode(const NinjaNode& nn, std::ostream& out) {
    const DepNode* node = nn.node;
    // Ninja needs a concrete local output for a rule-bearing VPATH target.
    // Materialize a local link to the source only while its ordinary
    // prerequisites are older. This keeps the rule's edges reachable and
    // gives parent recipes a usable logical filename. The link follows later
    // source updates without copying stale contents into the build tree.
    std::vector<Command> commands = nn.commands;
    const bool vpath_output = node->vpath_provider.IsValid() && !node->is_phony;
    if (vpath_output && commands.empty()) {
      Command materialize(node->output);
      materialize.cmd = ":";
      materialize.echo = false;
      commands.push_back(std::move(materialize));
    }

    // Make distinguishes "doc" from "doc/", but Ninja normalizes both to
    // the same path.  If the directory already exists and "doc" is another
    // target, the directory recipe is unnecessary and would emit a duplicate
    // Ninja output.  Its prerequisite edges are omitted for the same reason.
    if (IsExistingDirectoryAlias(node->output))
      return;

    // An existing source file may match a silent dummy rule such as FFmpeg's
    // "%.h:; @:". It is an input, not a generated output: declaring it as an
    // output would make "ninja -t clean" delete the source file.
    struct stat existing_output;
    if (!node->is_phony && node->deps.empty() && node->order_onlys.empty() &&
        node->validations.empty() && commands.size() == 1 &&
        !commands.front().echo && commands.front().cmd == ":" &&
        stat(node->output.c_str(), &existing_output) == 0 &&
        S_ISREG(existing_output.st_mode))
      return;

    std::string rule_name = "phony";
    // Ninja owns the build-time job budget. Do not impose a second fixed
    // pool from Kati's graph-generation -j value; ninja.sh exports the
    // runtime value to recursive Kati processes.
    bool use_local_pool = false;
    if (IsSpecialTarget(node->output)) {
      return;
    }
    if (g_flags.enable_debug) {
      out << "# " << (node->loc.filename ? node->loc.filename : "(null)") << ':'
          << node->loc.lineno << "\n";
    }
    if (!commands.empty()) {
      std::string description = "build $out";
      std::string cmd_buf;
      const std::string command_shell =
          commands.front().shell.empty() ? shell_
                                         : EscapeNinja(commands.front().shell);
      const std::string command_shellflag =
          commands.front().shellflag.empty()
              ? shell_flags_
              : EscapeNinja(commands.front().shellflag);
      GenShellScript(node->output.c_str(), commands, &cmd_buf, &description,
                     node->oneshell);
      // Recipe translation may remove every command.  Keep the Ninja rule a
      // valid shell no-op, including when the leaf-output guard is added.
      if (cmd_buf.empty())
        cmd_buf = ":";
      if (vpath_output) {
        const std::string output = ShellQuote(node->output.str());
        const std::string provider = ShellQuote(node->vpath_provider.str());
        std::string current = "if { [ ! -e " + output + " ] || [ -L " + output +
                              " ]; } && [ -e " + provider + " ]";
        std::string local_current =
            "if [ -e " + output + " ] && [ ! -L " + output + " ]";
        for (const NamedDepNode& dep : node->deps) {
          // A prerequisite-only rule retains its provider even when a
          // prerequisite is newer: there is no recipe to replace it.
          if (node->cmds.empty())
            break;
          if (dep.second->is_phony) {
            current += " && false";
            local_current += " && false";
            break;
          }
          const std::string input = ShellQuote(dep.first.str());
          current += " && [ -e " + input + " ] && [ ! " + input + " -nt " +
                     provider + " ]";
          local_current += " && [ -e " + input + " ] && [ ! " + input +
                           " -nt " + output + " ]";
        }
        const std::string link_target =
            node->vpath_provider.str().front() == '/'
                ? std::string(node->vpath_provider.str())
                : working_dir_ + "/" + node->vpath_provider.str();
        std::string materialize = "rm -f " + output + " && ln -s " +
                                  ShellQuote(link_target) + " " + output;
        const std::string_view parent = Dirname(node->output.str());
        if (!parent.empty() && parent != ".")
          materialize = "mkdir -p " + ShellQuote(parent) + " && " + materialize;
        cmd_buf = local_current + "; then :; el" + current + "; then " +
                  materialize + "; else " + "if [ -L " + output +
                  " ]; then rm -f " + output + "; fi; " + cmd_buf + "; fi";
      }
      // Ninja has no build-log entry for files that predate a newly emitted
      // graph, and runs their recipes even when make would find them current.
      // OpenSSL's configdata.pm recipe deliberately fails after reconfiguring,
      // so the first Ninja run must honor the ordinary timestamp fast path.
      // Phony and validation prerequisites retain their usual Ninja behavior.
      const bool has_phony_input = std::any_of(
          node->deps.begin(), node->deps.end(),
          [](const NamedDepNode& dep) { return dep.second->is_phony; });
      // Order-only prerequisites may run, but they do not make an existing
      // output stale. Ninja has no prior build-log entry for such an output.
      if (!vpath_output && !node->is_phony && node->deps.empty() &&
          node->validations.empty()) {
        cmd_buf = "if [ -e " + ShellQuote(node->output.str()) +
                  " ]; then :; else " + cmd_buf + "; fi";
      } else if (!vpath_output && !node->is_phony && !node->deps.empty() &&
                 !has_phony_input && node->validations.empty() &&
                 Exists(node->output.str())) {
        const std::string output = ShellQuote(node->output.str());
        std::string current = "if [ -e " + output + " ]";
        for (const NamedDepNode& dep : node->deps) {
          const std::string input = ShellQuote(dep.first.str());
          current += " && [ -e " + input + " ] && [ ! " + input + " -nt " +
                     output + " ]";
        }
        cmd_buf = current + "; then :; else " + cmd_buf + "; fi";
      }
      // Recursive sub-builds remain serialized; recipe exports are prepared by
      // CommandEvaluator for both direct and Ninja execution.
      use_local_pool = IsRecursiveKatiCommand(cmd_buf);
      // The generated environment snapshot is part of Kati's graph output,
      // but users may invoke Ninja directly instead of using ninja.sh.  Load
      // that snapshot inside every recipe so exported make variables have the
      // same visibility in both entry paths.  The guard keeps graphs usable
      // with callers that intentionally provide their own environment.
      // GetFilename() may return an absolute path when --ninja_dir is
      // absolute.  Prefixing every result with "./" changes that path into
      // a relative one and makes the generated environment silently vanish.
      // Keep relative paths relative to the Ninja working directory, while
      // preserving absolute paths verbatim.
      const std::string env_script = GetEnvScriptFilename();
      const std::string env_script_ref =
          !env_script.empty() && env_script.front() == '/' ? env_script
                                                           : "./" + env_script;
      const std::string quoted_env_script = ShellQuote(env_script_ref);
      cmd_buf = "if [ -r " + quoted_env_script + " ]; then . " +
                quoted_env_script + "; fi; " + cmd_buf;
      // GNU make runs each recipe in the directory in which its makefile was
      // read. Ninja runs all recipes from the graph's invocation directory,
      // so recursive graphs otherwise resolve relative paths incorrectly.
      // Preserve make's directory semantics for every emitted recipe,
      // including the graph's environment snapshot.
      cmd_buf = "cd " + ShellQuote(working_dir_) + " && " + cmd_buf;

      // Ninja compares nanosecond timestamps, while GNU make treats
      // prerequisites named by .LOW_RESOLUTION_TIME as second-resolution
      // timestamps.  Ninja may therefore schedule this edge for a change
      // that GNU make would ignore.  Recheck the complete normal-prerequisite
      // set at recipe time and skip only when the edge is stale solely due to
      // a low-resolution prerequisite within the same second.
      const std::string output = ShellQuote(node->output.str());
      if (!node->low_resolution_inputs.empty()) {
        std::string guard = "kati_mtime() { stat -f %m \"$$1\"; }; ";
        guard += "if [ -e " + output + " ]; then ";
        guard += "kati_lowres_skip=1; ";
        guard += "kati_output_sec=$$(kati_mtime " + output + "); ";
        for (Symbol input : node->low_resolution_inputs) {
          guard += "if [ ! -e " + ShellQuote(input.str()) +
                   " ] || [ $$(kati_mtime " + ShellQuote(input.str()) +
                   ") -gt \"$$kati_output_sec\" ]; then "
                   "kati_lowres_skip=0; fi; ";
        }
        for (Symbol input : node->actual_inputs) {
          if (std::find(node->low_resolution_inputs.begin(),
                        node->low_resolution_inputs.end(),
                        input) != node->low_resolution_inputs.end())
            continue;
          guard += "if [ " + ShellQuote(input.str()) + " -nt " + output +
                   " ]; then kati_lowres_skip=0; fi; ";
        }
        guard += "if [ \"$$kati_lowres_skip\" -eq 1 ]; then exit 0; fi; fi; ";
        cmd_buf = guard + cmd_buf;
      }

      if (node->delete_on_error && !node->precious) {
        cmd_buf = "( " + cmd_buf +
                  " ); kati_status=$$?; "
                  "if [ $$kati_status -ne 0 ] && [ -e " +
                  output + " ] && [ ! -d " + output + " ]; then rm -f " +
                  output + "; fi; exit $$kati_status";
      }
      std::string depfile;
      const bool has_depfile = GetDepfile(node, &cmd_buf, &depfile);
      std::string rule_key = description;
      rule_key += '\0';
      rule_key += cmd_buf;
      rule_key += '\0';
      rule_key += command_shell;
      rule_key += '\0';
      rule_key += command_shellflag;
      rule_key += '\0';
      rule_key += has_depfile ? depfile : "";
      rule_key += '\0';
      rule_key += node->is_restat ? '1' : '0';
      rule_key += node->delete_on_error ? '1' : '0';
      rule_key += node->precious ? '1' : '0';
      rule_key += g_flags.emit_sandbox_disabled ? '1' : '0';
      if (cmd_buf.size() > 100 * 1000) {
        // Large recipes source a response file named after this output, so
        // they cannot share a Ninja rule with another output.
        rule_key += node->output.str();
      }

      auto existing_rule = rules_.find(rule_key);
      if (existing_rule != rules_.end()) {
        rule_name = existing_rule->second;
      } else {
        rule_name = StringPrintf("rule%d", rule_id_++);
        rules_.emplace(std::move(rule_key), rule_name);
        out << "rule " << rule_name << "\n";
        out << " description = " << description << "\n";
        if (has_depfile)
          out << " depfile = " << depfile << "\n deps = gcc\n";

        // It seems Linux is OK with ~130kB and Mac's limit is ~250kB.
        // TODO: Find this number automatically.
        if (cmd_buf.size() > 100 * 1000) {
          out << " rspfile = $out.rsp\n";
          out << " rspfile_content = " << cmd_buf << "\n";
          std::string rspfile = node->output.str() + ".rsp";
          if (rspfile.front() != '/')
            rspfile = "./" + rspfile;
          const std::string source_rspfile = ". " + ShellQuote(rspfile);
          out << " command = " << command_shell << ' ' << command_shellflag
              << ' ' << ShellQuote(source_rspfile) << "\n";
        } else {
          // Keep the recipe opaque to the shell that Ninja uses to launch the
          // command. The recipe itself may contain another shell invocation
          // and shell variables assigned earlier in that recipe (for example,
          // r=...; export r; ...). ShellQuote preserves the command until the
          // requested shell parses it.
          out << " command = " << command_shell << ' ' << command_shellflag
              << ' ' << ShellQuote(cmd_buf) << "\n";
        }
        if (node->is_restat)
          out << " restat = 1\n";
        if (g_flags.emit_sandbox_disabled)
          out << " sandbox_disabled = true\n";
      }
    }

    EmitBuild(nn, rule_name, use_local_pool || node->is_notparallel, out);
  }

  std::string EscapeNinja(const std::string& s) const {
    if (s.find_first_of("$: ") == std::string::npos)
      return s;
    std::string r;
    for (char c : s) {
      switch (c) {
        case '$':
        case ':':
        case ' ':
          r += '$';
          [[fallthrough]];
        default:
          r += c;
      }
    }
    return r;
  }

  std::string EscapeBuildTarget(Symbol s) const { return EscapeNinja(s.str()); }

  bool IsExistingDirectoryAlias(Symbol dependency) const {
    std::string_view path = dependency.str();
    if (path.empty() || path.back() != '/')
      return false;

    // Ninja canonicalizes a trailing slash, so an existing directory such
    // as "doc/" would resolve to the unrelated make target "doc".  Make
    // keeps those names distinct.  The directory already exists, so this
    // edge cannot create it and must not point at the other make target.
    while (!path.empty() && path.back() == '/')
      path.remove_suffix(1);
    struct stat st;
    return !path.empty() && done_.exists(Intern(path)) &&
           stat(dependency.c_str(), &st) == 0 && S_ISDIR(st.st_mode);
  }

  void EmitBuild(const NinjaNode& nn,
                 const std::string& rule_name,
                 bool use_local_pool,
                 std::ostream& out) {
    const DepNode* node = nn.node;
    struct stat output_stat;
    const bool directory_output =
        node->output == Intern(".") ||
        (stat(node->output.str().c_str(), &output_stat) == 0 &&
         S_ISDIR(output_stat.st_mode));
    std::string directory_marker;
    if (directory_output) {
      directory_marker = "__kati_directory_";
      for (char c : node->output.str())
        directory_marker += c == '/' ? '_' : c;
    }
    std::string target = EscapeBuildTarget(
        directory_output ? Intern(directory_marker) : node->output);
    out << "build " << target;
    if (!node->implicit_outputs.empty()) {
      out << " |";
      for (Symbol output : node->implicit_outputs) {
        out << " " << EscapeBuildTarget(output);
      }
    }
    out << ": " << rule_name;
    std::vector<Symbol> order_onlys;
    if (node->is_phony && !g_flags.use_ninja_phony_output) {
      out << " _kati_always_build_";
    }
    for (auto const& d : node->deps) {
      if (IsCycleEdge(node->output, d.first) ||
          IsExistingDirectoryAlias(d.first))
        continue;
      out << " " << EscapeBuildTarget(d.first).c_str();
    }
    if (node->vpath_provider.IsValid() && !node->is_phony)
      out << " " << EscapeBuildTarget(node->vpath_provider);
    bool has_order_only = false;
    for (auto const& d : node->order_onlys) {
      if (IsCycleEdge(node->output, d.first) ||
          IsExistingDirectoryAlias(d.first))
        continue;
      if (!has_order_only)
        out << " ||";
      has_order_only = true;
      out << " " << EscapeBuildTarget(d.first).c_str();
    }
    bool has_validation = false;
    for (auto const& d : node->validations) {
      if (IsCycleEdge(node->output, d.first) ||
          IsExistingDirectoryAlias(d.first))
        continue;
      if (!has_validation)
        out << " |@";
      has_validation = true;
      out << " " << EscapeBuildTarget(d.first).c_str();
    }

    out << "\n";

    // Ninja removes an edge's declared outputs when the edge is interrupted.
    // A recursive make target can legitimately be an existing directory, so
    // declaring that directory as the command output makes interruption try
    // to unlink it (for example, remove(.)). Use a synthetic marker for the
    // command and retain the logical directory as a phony alias.
    if (directory_output) {
      out << "build " << EscapeBuildTarget(node->output) << ": phony "
          << EscapeBuildTarget(Intern(directory_marker)) << "\n";
    }

    std::string pool;
    if (node->ninja_pool_var) {
      node->ninja_pool_var->Eval(ev_, &pool);
    }

    if (pool != "") {
      if (pool != "none") {
        out << " pool = " << pool << "\n";
      }
    } else if (g_flags.default_pool && rule_name != "phony") {
      out << " pool = " << g_flags.default_pool << "\n";
    } else if (use_local_pool) {
      out << " pool = local_pool\n";
    }
    if (node->is_phony && g_flags.use_ninja_phony_output) {
      out << " phony_output = true\n";
    }
    if (node->tags_var) {
      std::string tags;
      node->tags_var->Eval(ev_, &tags);
      if (!tags.empty()) {
        out << " tags = " << tags << "\n";
      }
    }
    if (node->is_default_target) {
      std::unique_lock<std::mutex> lock(mu_);
      default_target_ = node;
    }
  }

  static std::string GetEnvScriptFilename() { return GetFilename("env%s.sh"); }

  void PrintStats() const {
    size_t dependency_edges = 0;
    size_t recipe_nodes = 0;
    size_t recipe_commands = 0;
    size_t recursive_edges = 0;
    size_t pool_annotations = 0;
    size_t max_dependencies = 0;
    size_t phony_nodes = 0;
    size_t leaf_recipes = 0;
    size_t critical_path = 0;
    std::unordered_map<Symbol, size_t> depths;
    std::unordered_set<Symbol> visiting;

    auto get_depth = [&](const auto& self, const DepNode* node) -> size_t {
      auto cached = depths.find(node->output);
      if (cached != depths.end())
        return cached->second;
      // A circular make dependency is invalid for a build path, but Kati can
      // still represent it while diagnosing the graph. Break the diagnostic
      // cycle without affecting the generated Ninja graph.
      if (!visiting.insert(node->output).second)
        return 0;
      size_t depth = 1;
      for (const auto& dependency : node->deps)
        depth = std::max(depth, 1 + self(self, dependency.second));
      for (const auto& dependency : node->order_onlys)
        depth = std::max(depth, 1 + self(self, dependency.second));
      for (const auto& dependency : node->validations)
        depth = std::max(depth, 1 + self(self, dependency.second));
      visiting.erase(node->output);
      depths.emplace(node->output, depth);
      return depth;
    };

    for (const NinjaNode& ninja_node : nodes_) {
      const DepNode* node = ninja_node.node;
      const size_t dependencies = node->deps.size() + node->order_onlys.size() +
                                  node->validations.size();
      dependency_edges += dependencies;
      if (dependencies > max_dependencies)
        max_dependencies = dependencies;
      if (node->is_phony)
        ++phony_nodes;
      if (node->ninja_pool_var != nullptr)
        ++pool_annotations;
      if (!ninja_node.commands.empty())
        ++recipe_nodes;
      if (!ninja_node.commands.empty() && dependencies == 0)
        ++leaf_recipes;
      critical_path = std::max(critical_path, get_depth(get_depth, node));
      for (const Command& command : ninja_node.commands) {
        ++recipe_commands;
        if (command.cmd.find("KATI_DEPTH=") != std::string::npos) {
          ++recursive_edges;
        }
      }
    }

    fprintf(stderr,
            "kati: Ninja graph stats: nodes=%zu recipes=%zu commands=%zu "
            "dependencies=%zu phony=%zu recursive=%zu pools=%zu "
            "max_dependencies=%zu leaf_recipes=%zu critical_path=%zu\n",
            nodes_.size(), recipe_nodes, recipe_commands, dependency_edges,
            phony_nodes, recursive_edges, pool_annotations, max_dependencies,
            leaf_recipes, critical_path);
    if (recursive_edges != 0) {
      fprintf(stderr,
              "kati: Ninja scheduling note: recursive commands hide their "
              "child graph from Ninja; inspect child Kati scheduling too.\n");
    }
  }

  void GenerateNinja() {
    ScopedTimeReporter tr("ninja gen (emit)");
    const std::string filename = GetNinjaFilename();
    const std::string temporary = filename + ".tmp";
    std::ofstream out(temporary, std::ios::binary);
    if (!out)
      PERROR("fopen(build.ninja) failed");

    out << "# Generated by kati " << kGitVersion << "\n\n";

    // Recursive make boundaries are intentionally serialized.  Their
    // internal dependency graphs are opaque to this Ninja graph, so Ninja
    // cannot otherwise know about shared outputs produced by sibling
    // recursive invocations.
    out << "pool local_pool\n depth = 1\n\n";

    if (!used_envs_.empty()) {
      out << "# Environment variables used:\n";
      for (const auto& [key, value] : used_envs_) {
        out << "# " << key << "=" << value << '\n';
      }
      out << '\n';
    }

    if (!g_flags.no_ninja_prelude) {
      if (g_flags.ninja_dir) {
        out << "builddir = " << g_flags.ninja_dir << "\n\n";
      }

      if (!g_flags.use_ninja_phony_output) {
        out << "build _kati_always_build_: phony\n\n";
      }
    }

    if (!g_flags.generate_empty_ninja) {
      SymbolSet outputs;
      for (const auto& node : nodes_) {
        outputs.insert(node.node->output);
        for (Symbol output : node.node->implicit_outputs)
          outputs.insert(output);
      }
      SymbolSet providers;
      for (const auto& node : nodes_) {
        Symbol provider = node.node->vpath_provider;
        if (!provider.IsValid() || node.node->is_phony ||
            outputs.exists(provider) || providers.exists(provider))
          continue;
        providers.insert(provider);
        // A provider is optional once a recipe has produced a local file.
        // A phony leaf preserves its real timestamp while it exists and
        // lets the output's runtime guard handle disappearance safely.
        out << "build " << EscapeBuildTarget(provider) << ": phony\n\n";
      }
      for (const auto& node : nodes_) {
        EmitNode(node, out);
      }

      std::string default_targets;
      if (g_flags.targets.empty() || g_flags.gen_all_targets) {
        CHECK(default_target_);
        default_targets = EscapeBuildTarget(default_target_->output);
      } else {
        for (Symbol s : g_flags.targets) {
          if (!default_targets.empty())
            default_targets += ' ';
          default_targets += EscapeBuildTarget(s);
        }
      }

      std::vector<Symbol> intermediate_outputs;
      std::unordered_set<Symbol> seen_intermediates;
      for (const NinjaNode& ninja_node : nodes_) {
        const DepNode* node = ninja_node.node;
        if (node->intermediate &&
            seen_intermediates.insert(node->output).second)
          intermediate_outputs.push_back(node->output);
      }
      if (!intermediate_outputs.empty()) {
        const std::string cleanup_target = ".kati_intermediate_cleanup";
        out << "\nrule kati_intermediate_cleanup\n"
            << " command = " << shell_ << ' ' << shell_flags_ << ' ';
        std::string cleanup_command = "rm -f --";
        for (Symbol output : intermediate_outputs) {
          cleanup_command += " ";
          cleanup_command += ShellQuote(output.str());
        }
        cleanup_command += " && touch \"$out\"";
        out << ShellQuote(cleanup_command) << "\n"
            << "build " << cleanup_target << ": kati_intermediate_cleanup | "
            << default_targets << "\n";
        default_targets = cleanup_target;
      }
      out << "\n"
          << "default " << default_targets << '\n';
    }

    if (g_flags.ninja_stats)
      PrintStats();

    SymbolSet used_env_vars(Vars::used_env_vars());
    // PATH changes $(shell).
    used_env_vars.insert(Intern("PATH"));
    for (Symbol e : used_env_vars) {
      std::string_view val(getenv(e.c_str()));
      used_envs_.emplace(e.str(), std::string(val));
    }
    out.close();
    if (!out)
      PERROR("write(build.ninja) failed");
    if (rename(temporary.c_str(), filename.c_str()) != 0)
      PERROR("rename(build.ninja) failed");
  }

  void GenerateShell() {
    const std::string env_filename = GetEnvScriptFilename();
    const std::string env_temporary = env_filename + ".tmp";
    FILE* fp = fopen(env_temporary.c_str(), "wb");
    if (fp == NULL)
      PERROR("fopen(env.sh) failed");

    fprintf(fp, "#!/bin/sh\n");
    fprintf(fp, "# Generated by kati %s\n", kGitVersion);
    fprintf(fp, "\n");

    std::unordered_set<std::string> emitted_exports;
    emitted_exports.insert("MAKELEVEL");
    fprintf(fp, "export MAKELEVEL=%d\n", g_flags.make_level + 1);
    for (const auto& [symbol, is_exported] : ev_->exports()) {
      if (symbol.str() == "MAKELEVEL")
        continue;
      if (!IsShellIdentifier(symbol.str())) {
        continue;
      }

      emitted_exports.insert(symbol.str());

      if (is_exported) {
        std::string val = ev_->EvalVar(symbol);
        const std::string quoted_symbol = ShellQuote(symbol.str());
        const std::string quoted_val = ShellQuote(val);
        fprintf(fp, "export %s=%s\n", quoted_symbol.c_str(),
                quoted_val.c_str());
      } else {
        const std::string quoted_symbol = ShellQuote(symbol.str());
        fprintf(fp, "unset %s\n", quoted_symbol.c_str());
      }
    }

    // GNU make always propagates these special recursive-make variables.
    // They are not consistently represented as ordinary user exports in
    // Kati's symbol table: Kbuild's explicit `export MAKE`, for example, can
    // be lost while the bootstrap variable is still defined.  Omitting them
    // from a deferred Ninja recipe either makes quoted "$MAKE" fail or loses
    // command-line assignments (for example LLVM=1).  Keep MAKE separate from
    // its arguments: it must remain one exact executable pathname, while
    // MAKEFLAGS carries the recursive invocation state.
    for (const char* special : {"MAKE", "MAKEFLAGS", "MAKEOVERRIDES"}) {
      const Symbol symbol = Intern(special);
      Var* value = ev_->LookupVar(symbol);
      if (value == nullptr || !value->IsDefined())
        continue;

      // An ordinary export above already emitted the value.  MAKE is still
      // emitted here when the export table did not retain Kbuild's special
      // export declaration.
      if (emitted_exports.count(symbol.str()))
        continue;

      const std::string val = ev_->EvalVar(symbol);
      const std::string quoted_symbol = ShellQuote(symbol.str());
      const std::string quoted_val = ShellQuote(val);
      fprintf(fp, "export %s=%s\n", quoted_symbol.c_str(), quoted_val.c_str());
    }

    if (fclose(fp) != 0)
      PERROR("fclose(env.sh) failed");
    if (rename(env_temporary.c_str(), env_filename.c_str()) != 0)
      PERROR("rename(env.sh) failed");

    const std::string launcher_filename = GetNinjaShellScriptFilename();
    const std::string launcher_temporary = launcher_filename + ".tmp";
    fp = fopen(launcher_temporary.c_str(), "wb");
    if (fp == NULL)
      PERROR("fopen(ninja.sh) failed");

    fprintf(fp, "#!/bin/sh\n");
    fprintf(fp, "# Generated by kati %s\n", kGitVersion);
    fprintf(fp, "\n");

    fprintf(fp, ". %s\n", GetEnvScriptFilename().c_str());

    // Build-time parallelism belongs to Ninja, not graph generation.
    // Propagate the runtime -j value to recursive Kati commands without
    // requiring callers to know about Kati's internal scheduling metadata.
    // Match Ninja's normal host-parallel default for recursive Kati work.
    // An explicit runtime -j option still overrides this value below.
    fprintf(fp, "kati_jobs=\"${KATI_JOBS:-}\"\n");
    fprintf(fp, "kati_jobs_explicit=0\n");
    fprintf(fp, "if [ -n \"$kati_jobs\" ]; then kati_jobs_explicit=1; fi\n");
    fprintf(fp, "default_kati_jobs=%d\n",
            g_flags.num_cpus > 0 ? g_flags.num_cpus : 1);
    fprintf(fp, "ninja_jobs=\"\"\n");
    fprintf(fp, "prev=\"\"\n");
    fprintf(fp, "for arg in \"$@\"; do\n");
    fprintf(fp, "  case \"$arg\" in\n");
    fprintf(fp, "    -j[0-9]*) ninja_jobs=\"${arg#-j}\" ;;\n");
    fprintf(fp, "    -j=*) ninja_jobs=\"${arg#-j=}\" ;;\n");
    fprintf(fp, "    -j) prev=\"-j\" ;;\n");
    fprintf(fp,
            "    [0-9]*) if [ \"$prev\" = \"-j\" ]; then ninja_jobs=\"$arg\"; "
            "prev=\"\"; fi ;;\n");
    fprintf(fp, "    *) prev=\"\" ;;\n");
    fprintf(fp, "  esac\n");
    fprintf(fp, "done\n");
    fprintf(fp, "if [ \"$kati_jobs_explicit\" -eq 0 ]; then\n");
    fprintf(fp, "  kati_jobs=\"${ninja_jobs:-$default_kati_jobs}\"\n");
    fprintf(fp, "fi\n");
    fprintf(
        fp,
        "if [ -n \"$kati_jobs\" ]; then export KATI_JOBS=\"$kati_jobs\"; fi\n");

    // Recursive Kati processes are invisible to Ninja's scheduler. Give them
    // one shared byte-token FIFO so nested Kati executors consume the same
    // runtime budget instead of multiplying it at every recursion level.
    fprintf(fp, "kati_fifo=\"\"\n");
    fprintf(fp, "if [ -z \"${KATI_JOBSERVER_FIFO:-}\" ]; then\n");
    fprintf(fp,
            "  case \"$kati_jobs\" in ''|0|*[!0-9]*) kati_jobs=1; export "
            "KATI_JOBS=1 ;; esac\n");
    fprintf(fp, "  kati_fifo_base=\"${TMPDIR:-/tmp}/kati-jobserver-$$\"\n");
    fprintf(fp, "  kati_fifo=\"$kati_fifo_base\"\n");
    fprintf(fp, "  kati_fifo_i=0\n");
    fprintf(fp,
            "  while ! (umask 077 && mkfifo \"$kati_fifo\") 2>/dev/null; do\n");
    fprintf(fp, "    kati_fifo_i=$((kati_fifo_i + 1))\n");
    fprintf(fp, "    kati_fifo=\"$kati_fifo_base-$kati_fifo_i\"\n");
    fprintf(fp, "  done\n");
    fprintf(fp, "  exec 9<>\"$kati_fifo\"\n");
    fprintf(fp, "  kati_i=0\n");
    fprintf(fp,
            "  while [ \"$kati_i\" -lt \"$kati_jobs\" ]; do printf x >&9; "
            "kati_i=$((kati_i + 1)); done\n");
    fprintf(fp, "  export KATI_JOBSERVER_FIFO=\"$kati_fifo\"\n");
    fprintf(fp,
            "  trap 'if [ -n \"${kati_fifo:-}\" ]; then rm -f \"$kati_fifo\"; "
            "fi' EXIT HUP INT TERM\n");
    fprintf(fp, "fi\n");

    // Keep Ninja as a child so the wrapper can cleanly terminate it before
    // removing the shared FIFO.  An exec-only wrapper cannot reap or signal
    // Ninja's recursive command tree when the wrapper receives an interrupt;
    // that can leave recursive Kati processes alive and corrupt the next
    // incremental attempt by racing the same output directory.
    fprintf(fp, "kati_ninja_pid=\"\"\n");
    fprintf(fp, "kati_cleanup() {\n");
    fprintf(fp,
            "  if [ -n \"$kati_ninja_pid\" ]; then kill -TERM "
            "\"$kati_ninja_pid\" 2>/dev/null || :; fi\n");
    fprintf(fp,
            "  if [ -n \"${kati_fifo:-}\" ]; then rm -f \"$kati_fifo\"; fi\n");
    fprintf(fp, "}\n");
    fprintf(fp, "trap 'kati_cleanup; exit 129' HUP INT TERM\n");
    fprintf(fp, "ninja -f %s ", GetNinjaFilename().c_str());
    if (g_flags.remote_num_jobs > 0) {
      fprintf(fp, "-j%d ", g_flags.remote_num_jobs);
    }
    fprintf(fp, "\"$@\" &\n");
    fprintf(fp, "kati_ninja_pid=$!\n");
    fprintf(fp, "wait \"$kati_ninja_pid\"\n");
    fprintf(fp, "kati_status=$?\n");
    fprintf(fp, "kati_ninja_pid=\"\"\n");
    fprintf(fp, "trap - HUP INT TERM\n");
    fprintf(fp, "if [ -n \"$kati_fifo\" ]; then rm -f \"$kati_fifo\"; fi\n");
    fprintf(fp, "exit $kati_status\n");

    if (fclose(fp) != 0)
      PERROR("fclose(ninja.sh) failed");

    if (chmod(launcher_temporary.c_str(), 0755) != 0)
      PERROR("chmod ninja.sh failed");
    if (rename(launcher_temporary.c_str(), launcher_filename.c_str()) != 0)
      PERROR("rename(ninja.sh) failed");
  }

  void GenerateStamp(const std::string& orig_args) {
    FILE* fp = fopen(GetStampTempFilename().c_str(), "wb");
    CHECK(fp);

    size_t r = fwrite(&start_time_, sizeof(start_time_), 1, fp);
    CHECK(r == 1);
    CHECK(fwrite("KAT2", 1, 4, fp) == 4);

    std::unordered_set<std::string> makefiles;
    MakefileCacheManager::Get().GetAllFilenames(&makefiles);
    DumpInt(fp, makefiles.size() + 1);
    DumpString(fp, kati_binary_);
    for (const std::string& makefile : makefiles) {
      DumpString(fp, makefile);
    }

    DumpInt(fp, Evaluator::used_undefined_vars().size());
    for (Symbol v : Evaluator::used_undefined_vars()) {
      DumpString(fp, v.str());
    }
    DumpInt(fp, used_envs_.size());
    for (const auto& [key, value] : used_envs_) {
      DumpString(fp, key);
      DumpString(fp, value);
    }

    auto& globs = GetAllGlobCache();
    DumpInt(fp, globs.size());
    for (const auto& [key, files] : globs) {
      DumpString(fp, key);
#if 0
      std::unordered_set<std::string> dirs;
      GetReadDirs(p.first, files, &dirs);
      DumpInt(fp, dirs.size());
      for (const std::string& dir : dirs) {
        DumpString(fp, dir);
      }
#endif
      DumpInt(fp, files.size());
      for (const std::string& file : files) {
        DumpString(fp, file);
      }
    }

    const std::vector<CommandResult*>& crs = GetShellCommandResults();
    DumpInt(fp, crs.size());
    for (CommandResult* cr : crs) {
      DumpInt(fp, static_cast<int>(cr->op));
      DumpString(fp, cr->shell);
      DumpString(fp, cr->shellflag);
      DumpString(fp, cr->cmd);
      DumpString(fp, cr->result);
      DumpString(fp, cr->loc.filename);
      DumpInt(fp, cr->loc.lineno);

      if (cr->op == CommandOp::FIND) {
        std::vector<std::string> missing_dirs;
        for (std::string_view fd : cr->find->finddirs) {
          const std::string& d = ConcatDir(cr->find->chdir, fd);
          if (!Exists(d))
            missing_dirs.push_back(d);
        }
        DumpInt(fp, missing_dirs.size());
        for (const std::string& d : missing_dirs) {
          DumpString(fp, d);
        }

        DumpInt(fp, cr->find->found_files->size());
        for (std::string_view s : *cr->find->found_files) {
          DumpString(fp, ConcatDir(cr->find->chdir, s));
        }

        DumpInt(fp, cr->find->read_dirs->size());
        for (std::string_view s : *cr->find->read_dirs) {
          DumpString(fp, ConcatDir(cr->find->chdir, s));
        }
      }
    }

    DumpString(fp, orig_args);

    if (fclose(fp) != 0)
      PERROR("fclose(kati_stamp) failed");
    if (rename(GetStampTempFilename().c_str(),
               GetNinjaStampFilename().c_str()) != 0)
      PERROR("rename(kati_stamp) failed");
  }

  CommandEvaluator ce_;
  Evaluator* ev_;
  SymbolSet done_;
  std::unordered_set<std::string> active_nodes_;
  std::unordered_set<std::string> cycle_edges_;
  int rule_id_;
  std::unordered_map<std::string, std::string> rules_;
  const std::string shell_;
  const std::string shell_flags_;
  std::map<std::string, std::string> used_envs_;
  const std::string kati_binary_;
  std::string working_dir_;
  const double start_time_;
  std::vector<NinjaNode> nodes_;

  std::mutex mu_;
  const DepNode* default_target_;
};

std::string GetNinjaFilename() {
  return NinjaGenerator::GetFilename("build%s.ninja");
}

std::string GetNinjaShellScriptFilename() {
  return NinjaGenerator::GetFilename("ninja%s.sh");
}

std::string GetEnvScriptFilename() {
  return NinjaGenerator::GetFilename("env%s.sh");
}

std::string GetNinjaStampFilename() {
  return NinjaGenerator::GetFilename(".kati_stamp%s");
}

void GenerateNinja(const std::vector<NamedDepNode>& nodes,
                   Evaluator* ev,
                   const std::string& orig_args,
                   double start_time) {
  NinjaGenerator ng(ev, start_time);
  ng.Generate(nodes, orig_args);
}
